# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-16 11:55
from __future__ import unicode_literals

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                ("flight_number", models.CharField(max_length=200, unique=True)),
                ("airline", models.CharField(max_length=200)),
                ("schedule_delay", models.PositiveIntegerField(default=0)),
                (
                    "informations_file",
                    models.FileField(
                        default="flights_info/crawler_result.json",
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/home/ali/PycharmProjects/airplane_tracking/media"
                        ),
                        upload_to="flights_info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("longitude", models.DecimalField(decimal_places=3, max_digits=6)),
                ("latitude", models.DecimalField(decimal_places=3, max_digits=6)),
                ("arrival_time", models.DateTimeField()),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.Flight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("schedule_delay", models.PositiveIntegerField(default=0)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_users",
                        to="tracking.Flight",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_flights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flight",
            name="user",
            field=models.ManyToManyField(
                related_name="flights",
                through="tracking.FlightUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
