# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-16 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flightuser",
            unique_together=set([("user", "flight")]),
        ),
    ]
