# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-16 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_auto_20210216_1613"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="user",
            new_name="users",
        ),
    ]
