# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-18 13:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_auto_20210216_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="schedule_delay",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="flightuser",
            name="schedule_delay",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
